<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Sign in to WebClient_email-address</name>
   <tag></tag>
   <elementGuidId>a0392897-2981-4a0c-8d22-eef7611f3331</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;email-address&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='email-address']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Email address&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>97b9d2b5-f5ef-4c2e-9360-5d5011252116</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-component</name>
      <type>Main</type>
      <value>atoms-element-input-1</value>
      <webElementGuid>3697b5cc-c4e2-4435-9b6f-d788bddabda3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> o-form__element</value>
      <webElementGuid>09e38547-27de-454d-b2c8-8be8e91d2edb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>ad09b97c-a732-4866-b362-215afe372840</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>email-address</value>
      <webElementGuid>9fa71938-3366-4ff9-9940-263909562cbc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-hook</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>92cd1fa4-7692-44ce-895f-ce98ebe17364</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content&quot;)/main[@class=&quot;o-external__main&quot;]/form[@class=&quot;o-card c-card&quot;]/div[@class=&quot;o-card__main&quot;]/div[@class=&quot;o-card__content&quot;]/section[@class=&quot;o-card__section  o-card__section--form&quot;]/label[@class=&quot;o-input o-form__object molecules-input&quot;]/input[@class=&quot;o-form__element&quot;]</value>
      <webElementGuid>8cb14ae0-b77a-4d7e-938e-90a43e1cf522</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='email-address']</value>
      <webElementGuid>73cb3eb5-759a-4843-8bac-9ed6fa11782b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/main/form/div/div/section[2]/label/input</value>
      <webElementGuid>ed438cb3-2681-4a45-8177-626f75f4ec6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>401658ed-acf6-4889-b6ae-35b02cb4cf14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'email' and @name = 'email-address']</value>
      <webElementGuid>07f6a048-8734-46b4-883e-cd498d17a671</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
